# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 19) do

  create_table "bookmarks", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "user_id"
    t.integer  "recipe_id"
  end

  add_index "bookmarks", ["user_id"], :name => "index_bookmarks_on_user_id"
  add_index "bookmarks", ["recipe_id"], :name => "index_bookmarks_on_recipe_id"

  create_table "comments", :force => true do |t|
    t.integer  "user_id"
    t.integer  "recipe_id"
    t.text     "body"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "comments", ["user_id"], :name => "index_comments_on_user_id"
  add_index "comments", ["recipe_id"], :name => "index_comments_on_recipe_id"

  create_table "ingredients", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "name"
    t.integer  "requirements_count", :default => 0, :null => false
    t.string   "url"
  end

  add_index "ingredients", ["name"], :name => "index_ingredients_on_name"
  add_index "ingredients", ["url"], :name => "index_ingredients_on_url"

  create_table "ratings", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "user_id"
    t.integer  "recipe_id"
    t.integer  "value",      :default => 0, :null => false
  end

  add_index "ratings", ["user_id"], :name => "index_ratings_on_user_id"
  add_index "ratings", ["recipe_id"], :name => "index_ratings_on_recipe_id"

  create_table "recipes", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "user_id"
    t.string   "name"
    t.text     "process"
    t.decimal  "rating",     :precision => 3, :scale => 2, :default => 0.0, :null => false
  end

  add_index "recipes", ["user_id"], :name => "index_recipes_on_user_id"

  create_table "requirements", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "recipe_id"
    t.integer  "ingredient_id"
    t.integer  "position"
    t.string   "quantity"
  end

  add_index "requirements", ["recipe_id"], :name => "index_requirements_on_recipe_id"
  add_index "requirements", ["ingredient_id"], :name => "index_requirements_on_ingredient_id"

  create_table "taggings", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "tag_id"
    t.integer  "recipe_id"
    t.integer  "user_id"
  end

  add_index "taggings", ["tag_id"], :name => "index_taggings_on_tag_id"
  add_index "taggings", ["recipe_id"], :name => "index_taggings_on_recipe_id"
  add_index "taggings", ["user_id"], :name => "index_taggings_on_user_id"

  create_table "tags", :force => true do |t|
    t.string  "name"
    t.integer "taggings_count", :default => 0, :null => false
    t.string  "url"
  end

  add_index "tags", ["name"], :name => "index_tags_on_name"
  add_index "tags", ["url"], :name => "index_tags_on_url"

  create_table "users", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "first_name"
    t.string   "last_name"
    t.string   "email"
    t.string   "password_hash"
    t.string   "password_salt"
    t.string   "password_reset_token"
    t.boolean  "administrator",        :default => false, :null => false
  end

  add_index "users", ["email"], :name => "index_users_on_email"

end
